# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-07 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('condition', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=20)),
                ('penciler', models.CharField(max_length=50)),
                ('cover_artist', models.CharField(max_length=50)),
            ],
        ),
    ]
