# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
