# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comic_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
